### ISSUE TITLE
Can it support jdk8？

### ISSUE THREAD

**Issue by eric-caiyao** [InfluxCommunity/influxdb3-java#104]

**Comment by bednar** [comment]
Hi @eric-caiyao, 

Currently, our project does not plan to support JDK versions lower than 11. The primary reason for this decision is our reliance on the HTTP client bundled with Java 11. This choice helps us minimize the impact of dependency conflicts for our customers, ensuring a smoother integration and usage experience.

However, we understand the importance of broad compatibility and are open to community contributions that could enhance our project's accessibility. If you, or anyone else, are capable of developing a solution that brings support for JDK 8 without introducing new dependencies, we would be more than happy to review such contributions. Integrating support for JDK 8, under these conditions, would indeed be a valuable addition to our codebase.

We appreciate the community's involvement and look forward to any pull requests that align with these guidelines. Your efforts to improve and extend the functionality of our project are genuinely valued.

Best regards
