### ISSUE TITLE
can`t use query with protobuf-java under 3.22

### ISSUE THREAD

**Issue by noam-stein** [InfluxCommunity/influxdb3-java#53]
### Specifications

* Install  protobuf-java 3.21.10
* call query
* Error:
```
Exception in thread "main" java.lang.IllegalAccessError: class org.apache.arrow.flight.impl.Flight$FlightDescriptor tried to access method 'com.google.protobuf.LazyStringArrayList com.google.protobuf.LazyStringArrayList.emptyList()' (org.apache.arrow.flight.impl.Flight$FlightDescriptor and com.google.protobuf.LazyStringArrayList are in unnamed module of loader 'app')
	at org.apache.arrow.flight.impl.Flight$FlightDescriptor.<init>(Flight.java:7034)
	at org.apache.arrow.flight.impl.Flight$FlightDescriptor.<clinit>(Flight.java:7738)
	at org.apache.arrow.flight.impl.FlightServiceGrpc.getGetFlightInfoMethod(FlightServiceGrpc.java:106)
```

### Code sample to reproduce problem

```java
  val manage = InfluxDbManager(host, token, database)
  val result = manage.query("SELECT * FROM  \"tes\" WHERE  time >= now() - interval '300 hour'", (data: Seq[AnyRef]) => data.head)
  println(result)
```

### Expected behavior

run the query

### Actual behavior

exception

### Additional info

related to:
https://github.com/quarkusio/quarkus/issues/31240

line in code:
<img width="1086" alt="image" src="https://github.com/InfluxCommunity/influxdb3-java/assets/15907201/0faf8aaf-80e5-4641-95fb-783179d36cf2">

**Comment by bednar** [comment]
Hi @noam-stein,

Thank you for using our client.

The `protobuf-java` dependency is utilized by `flight-grpc`. If you wish to use version `3.21`, you'll need to use [this version of flight-grpc](https://mvnrepository.com/artifact/org.apache.arrow/flight-grpc/12.0.0).

You can exclude `protobuf-java` and `flight-grpc` from `influxdb3-java` and add these dependencies separately in your `pom.xml` or Gradle configuration.

Regards

**Comment by noam-stein** [comment]
Thanks for the quick response.

unfortunately, I can't do it.
my project uses Bazel and some projects need flight-grpc latest version.

I can't really change that :-(

**Comment by bednar** [comment]
Which version of the `flight-grpc ` do you use?

**Comment by noam-stein** [comment]
`13.0.0`

**Comment by bednar** [comment]
Why you want to install `protobuf-java 3.21.10`? The `flight-grpc:13.0.0` depends on version `3.23.1`.

**Comment by noam-stein** [comment]
The project is a big monorepo.
I don't have control over the version of `protobuf-java`. I can't update `protobuf-java` in the whole project because there are a lot of breaking changes.

**Comment by bednar** [comment]
So, currently, you are using `flight-grpc:13.0.0` along with `protobuf-java:3.21.10`, and you also want to use `influxdb3-java:0.3.0`, correct?

**Comment by noam-stein** [comment]
thanks for the help,
I was able to update the dependencies
