### ISSUE TITLE
results for SQL queries have partial data

### ISSUE THREAD

**Issue by noam-stein** [InfluxCommunity/influxdb3-java#54]
### Specifications

*Java  Client Version:
0.3.0
* InfluxDB Version:
InfluxDB 3.0 (using Influxdb cloud)
* Java Version
11

### Code sample to reproduce problem

```Java
        try (InfluxDBClient client = InfluxDBClient.getInstance(host, token.toCharArray(), database)) {

            Point point1 = Point.measurement("players")
                    .addTag("user_name", "alice")
                    .addField("value", 2)
                    .setTimestamp(Instant.now());
            client.writePoint(point1);

            Point point2 = Point.measurement("players")
                    .addTag("user_name", "bob")
                    .addField("value", 1)
                    .setTimestamp(Instant.now());
            client.writePoint(point2);


            String sql = "SELECT user_name FROM players WHERE time >= to_timestamp_seconds(1697241600)::TIMESTAMP  group by user_name";
            try (Stream<Object[]> stream = client.query(sql)) {
                stream.forEach(row -> System.out.printf("|%s| %n", row[0]));
            }
        }
```

### Expected behavior

the result should include two names:
Bon and Alice.
from the UI
![image](https://github.com/InfluxCommunity/influxdb3-java/assets/15907201/5193d264-ad95-4a64-bd7e-c5c5d0a17d8d)

### Actual behavior

I see in the result:
Bob and Bob
from the code
![image](https://github.com/InfluxCommunity/influxdb3-java/assets/15907201/4caa5cf2-5f6a-4a9e-ac0e-71847fbe3c61)

### Additional info

for the query:
```SQL
SELECT  user_name FROM players WHERE time >= to_timestamp_seconds(1697241600)::TIMESTAMP"
```
the result from the db is equal to the result from UI,
and all the data is there.

**Comment by noam-stein** [comment]
was able to reproduce with a smaller example:
```SQL
SELECT name FROM (VALUES ( 'Alice', 4.56), ( 'Bob', 8.1)) AS data(name, value) group by name
```

**Comment by bednar** [comment]
Hi @noam-stein,

thanks for your reproducible example. 

I have prepared a fixed version within #55. Development version of the client will be available after #55 acceptance, stable version probably tomorrow.

Best

**Comment by bednar** [comment]
The development version of the client is deployed to snapshot repository. Tomorrow we will release the stable fixed version `0.3.1`.

https://oss.sonatype.org/content/repositories/snapshots/com/influxdb/influxdb3-java/0.4.0-SNAPSHOT/

**Comment by noam-stein** [comment]
@bednar 
when do you think you will publish `0.3.1` to maven repo?
I can't find it here
https://mvnrepository.com/artifact/com.influxdb/influxdb3-java

**Comment by bednar** [comment]
It is already release into Maven central. The mvnrepository.com has stale data:

- https://central.sonatype.com/artifact/com.influxdb/influxdb3-java
- https://repo1.maven.org/maven2/com/influxdb/influxdb3-java/0.3.1/
